### ISSUE TITLE
Friendly Reminder

### ISSUE THREAD

**Issue by Tylertron1998** [dirigeants/klasa-vscode#54]
Update the events to take user input for custom events

and also, I quote:

> uh, I can't remember what the changes were, but I asked the person making the pr to also pr to the extension, and I don't think that ever happened

**Comment by bdistin** [comment]
I don't think anyone has any way to remember what this was... Hopefully, it was addressed already.

**Comment by Tylertron1998** [comment]
I believe it was to just be able to write a custom name/event target, instead of just being stuck with the built in ones?
