### ISSUE TITLE
Your VS Code extension is affected by a security issue

### ISSUE THREAD

**Issue by auchenberg** [dirigeants/klasa-vscode#83]
Hi,

Kenneth here from the VS Code team.

Your extension is affected by https://code.visualstudio.com/blogs/2018/11/26/event-stream,

We will need to take action to block your extension if your extension isn't updated in a reasonable timeframe.

Please get in touch at kennau@microsoft.com

/k

**Comment by bdistin** [comment]
Hi, I believe #85 solves the issue highlighted here. After I finish updating deps, I will release a new version.

Thanks for the heads up!

**Comment by bdistin** [comment]
And after getting a new token, TravisCI has published the latest version: <https://travis-ci.com/dirigeants/klasa-vscode/jobs/161298896#L473-L476>

**Comment by auchenberg** [comment]
@bdistin You need to publish to the VS marketplace too.

**Comment by bdistin** [comment]
Yes, as seen in those linked logs, TravisCI has done exactly that.
